transporter:
  urls:
    direct_log: https://corporativo.directlog.com.br/track_individual/index.asp?numtracking=%s
    correios: https://www.linkcorreios.com.br/?id=%s
    madeira_madeira: https://eagle.madeiramadeira.com.br/tracking/mm/eventos?order=%s&collect=%s

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

server:
  port: 8080
